# Generated by Django 5.0.6 on 2024-09-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_stockdata_close_alter_stockdata_high_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockData',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
